// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sassoir.Api.Data;

#nullable disable

namespace Sassoir.Api.Migrations
{
    [DbContext(typeof(SassoirDbContext))]
    [Migration("20260717124838_ContactSubmissions")]
    partial class ContactSubmissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sassoir.Api.Data.AppUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_admin");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.ContactSubmissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasColumnName("submitted_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAtUtc")
                        .HasDatabaseName("ix_contact_submissions_submitted_at_utc");

                    b.ToTable("contact_submissions", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DateLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("date_label");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VenueAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("venue_address");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("venue_name");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.EventTableEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shape");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ZoneName")
                        .HasColumnType("text")
                        .HasColumnName("zone_name");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_tables", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.EventThemeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("background_color");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("hero_image_url");

                    b.Property<string>("HeroText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hero_text");

                    b.Property<string>("LogoText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo_text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_color");

                    b.Property<string>("SearchInputLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_input_label");

                    b.Property<string>("SearchPlaceholder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_placeholder");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secondary_color");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_color");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WelcomeTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("welcome_title");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("event_themes", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.FloorPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CanvasAspectRatio")
                        .HasColumnType("numeric")
                        .HasColumnName("canvas_aspect_ratio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("floor_plans", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.FloorPlanObjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Guid>("FloorPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("floor_plan_id");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid?>("LinkedTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_table_id");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_type");

                    b.Property<decimal>("Rotation")
                        .HasColumnType("numeric")
                        .HasColumnName("rotation");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shape");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.Property<decimal>("X")
                        .HasColumnType("numeric")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasColumnType("numeric")
                        .HasColumnName("y");

                    b.Property<int>("ZIndex")
                        .HasColumnType("integer")
                        .HasColumnName("z_index");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanId");

                    b.ToTable("floor_plan_objects", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.GuestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Directions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("directions");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("GroupLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_label");

                    b.Property<Guid?>("GuestGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_group_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("NormalizedSearchName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_search_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PersonCount")
                        .HasColumnType("integer")
                        .HasColumnName("person_count");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PublicToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_token");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("text")
                        .HasColumnName("seat_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TableId");

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.GuestMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("guest_messages", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.GuestSearchAliasEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_alias");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("guest_search_aliases", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.SearchMetricEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("NormalizedQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_query");

                    b.Property<bool>("Successful")
                        .HasColumnType("boolean")
                        .HasColumnName("successful");

                    b.HasKey("Id");

                    b.ToTable("search_metrics", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Sassoir.Api.Data.EventEntity", b =>
                {
                    b.HasOne("Sassoir.Api.Data.OrganizationEntity", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Sassoir.Api.Data.EventTableEntity", b =>
                {
                    b.HasOne("Sassoir.Api.Data.EventEntity", "Event")
                        .WithMany("Tables")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Sassoir.Api.Data.EventThemeEntity", b =>
                {
                    b.HasOne("Sassoir.Api.Data.EventEntity", "Event")
                        .WithOne("Theme")
                        .HasForeignKey("Sassoir.Api.Data.EventThemeEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Sassoir.Api.Data.FloorPlanEntity", b =>
                {
                    b.HasOne("Sassoir.Api.Data.EventEntity", "Event")
                        .WithMany("FloorPlans")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Sassoir.Api.Data.FloorPlanObjectEntity", b =>
                {
                    b.HasOne("Sassoir.Api.Data.FloorPlanEntity", "FloorPlan")
                        .WithMany("Objects")
                        .HasForeignKey("FloorPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FloorPlan");
                });

            modelBuilder.Entity("Sassoir.Api.Data.GuestEntity", b =>
                {
                    b.HasOne("Sassoir.Api.Data.EventEntity", "Event")
                        .WithMany("Guests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sassoir.Api.Data.EventTableEntity", "Table")
                        .WithMany("Guests")
                        .HasForeignKey("TableId");

                    b.Navigation("Event");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Sassoir.Api.Data.GuestMessageEntity", b =>
                {
                    b.HasOne("Sassoir.Api.Data.GuestEntity", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Sassoir.Api.Data.GuestSearchAliasEntity", b =>
                {
                    b.HasOne("Sassoir.Api.Data.GuestEntity", "Guest")
                        .WithMany("SearchAliases")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Sassoir.Api.Data.UserRoleEntity", b =>
                {
                    b.HasOne("Sassoir.Api.Data.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sassoir.Api.Data.AppUserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sassoir.Api.Data.AppUserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Sassoir.Api.Data.EventEntity", b =>
                {
                    b.Navigation("FloorPlans");

                    b.Navigation("Guests");

                    b.Navigation("Tables");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Sassoir.Api.Data.EventTableEntity", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("Sassoir.Api.Data.FloorPlanEntity", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("Sassoir.Api.Data.GuestEntity", b =>
                {
                    b.Navigation("SearchAliases");
                });

            modelBuilder.Entity("Sassoir.Api.Data.OrganizationEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Sassoir.Api.Data.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
